!<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>

        class ValidationError extends Error{
            constructor(message, field){
                super(message);
                this.field = field;
            }
        }
        class MathUtil{
            static sum(...numbers){
                
                if (numbers.length === 0){
                    // const error = new Error("Total parameter harus lebih dari 0");
                    // throw error;
                    throw new ValidationError ("Total parameter harus lebih dari 0", "numbers");
                }

                let total = 0;
                for (const number of numbers){
                    total += number;
                }
                return total;
            }
        }


        // ketika di try lancar tidak error maka catch tidak akan di eksekusi atau sebaliknya
        try{
            console.info(MathUtil.sum());
            console.info("rafli");
        }catch(error){
            if (error instanceof ValidationError){
                console.info(`Terjadi error di field ${error.field} dengan error ${error.message}`)
            }else{
                console.info(`Terjadi error : ${error.message}`);
            }
        }finally{
            console.info("program selesai")
        }
        console.info("Ramdhani");


    </script>
</body>
</html>